"""empty message

Revision ID: 211bd851fe6a
Revises: 19c0588d2ad3
Create Date: 2025-03-21 20:02:58.906716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211bd851fe6a'
down_revision = '19c0588d2ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('conteudo', sa.String(), nullable=True),
    sa.Column('data_postagem', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postagem')
    # ### end Alembic commands ###
