"""Cria tabela page_views para analytics

Revision ID: 26acdd793511
Revises: d073d2e3e5ee
Create Date: 2025-05-06 21:12:38.799731

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26acdd793511"
down_revision = "d073d2e3e5ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_views",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("visitor_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("page_views")
    # ### end Alembic commands ###
