"""empty message

Revision ID: 49316eb6cc2c
Revises: 8c9efe5d6f48
Create Date: 2025-03-24 21:23:55.109702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49316eb6cc2c'
down_revision = '8c9efe5d6f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem', schema=None) as batch_op:
        batch_op.drop_column('turma')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turma', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
