"""empty message

Revision ID: 6028d90c788a
Revises: dda675892320
Create Date: 2025-03-26 19:09:04.634016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6028d90c788a'
down_revision = 'dda675892320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
