"""empty message

Revision ID: 7c7b5fa864bb
Revises: a4918d76cc2d
Create Date: 2025-03-27 17:41:17.462878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7b5fa864bb'
down_revision = 'a4918d76cc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
