"""empty message

Revision ID: 8c9efe5d6f48
Revises: d1c86ba10b15
Create Date: 2025-03-24 21:22:01.901807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9efe5d6f48'
down_revision = 'd1c86ba10b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turma', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem', schema=None) as batch_op:
        batch_op.drop_column('turma')

    # ### end Alembic commands ###
