"""empty message

Revision ID: add9d711ddab
Revises: 7c7b5fa864bb
Create Date: 2025-03-27 20:45:30.133413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add9d711ddab'
down_revision = '7c7b5fa864bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_aula', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('material_mapa', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('material_exercicios', sa.Text(), nullable=True))
        batch_op.drop_column('materiais')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materiais', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('material_exercicios')
        batch_op.drop_column('material_mapa')
        batch_op.drop_column('material_aula')

    # ### end Alembic commands ###
