"""empty message

Revision ID: b0e6bc792f0f
Revises: 67c756e6742e
Create Date: 2025-03-26 21:38:31.147872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e6bc792f0f'
down_revision = '67c756e6742e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('titulo')
        batch_op.drop_column('destino')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titulo', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
