"""empty message

Revision ID: c537e01b1aee
Revises: 6028d90c788a
Create Date: 2025-03-26 21:36:37.243650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c537e01b1aee'
down_revision = '6028d90c788a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
