"""Adiciona coluna Gabarito na tabela Material

Revision ID: ce4c175d4b49
Revises: 26acdd793511
Create Date: 2025-05-12 16:15:28.976326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4c175d4b49'
down_revision = '26acdd793511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gabarito', sa.Text(), nullable=True))
        batch_op.alter_column('destino',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_index('ix_pageviews_path_occurred')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.create_index('ix_pageviews_path_occurred', ['path', 'occurred_at'], unique=False)

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('destino',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('gabarito')

    # ### end Alembic commands ###
