"""altera material_mapa_mental para material_resumo

Revision ID: d073d2e3e5ee
Revises: e170dc66d2b3
Create Date: 2025-04-15 16:25:42.598391

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d073d2e3e5ee"
down_revision = "e170dc66d2b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("material", schema=None) as batch_op:
        batch_op.add_column(sa.Column("resumo", sa.Text(), nullable=True))
        batch_op.drop_column("mapa_mental")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("material", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("mapa_mental", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("resumo")

    # ### end Alembic commands ###
