"""empty message

Revision ID: dae292ebcb82
Revises: add9d711ddab
Create Date: 2025-03-27 21:11:02.448338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae292ebcb82'
down_revision = 'add9d711ddab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('material_aula', sa.Text(), nullable=True),
    sa.Column('material_mapa', sa.Text(), nullable=True),
    sa.Column('material_exercicios', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    # ### end Alembic commands ###
