"""Migrando

Revision ID: e170dc66d2b3
Revises:
Create Date: 2025-04-15 16:15:03.857969

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e170dc66d2b3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("destino", sa.Integer(), nullable=True),
        sa.Column("titulo", sa.String(), nullable=True),
        sa.Column("aula", sa.Text(), nullable=True),
        sa.Column("mapa_mental", sa.Text(), nullable=True),
        sa.Column("lista_exercicios", sa.Text(), nullable=True),
        sa.Column("data_criacao", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("material")
    # ### end Alembic commands ###
