"""empty message

Revision ID: f99c33756c08
Revises: f60cd1cd79d2
Create Date: 2025-04-01 01:00:35.330369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99c33756c08'
down_revision = 'f60cd1cd79d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aula', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mapa_mental', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lista_exercicios', sa.Text(), nullable=True))
        batch_op.drop_column('materiais')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materiais', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('lista_exercicios')
        batch_op.drop_column('mapa_mental')
        batch_op.drop_column('aula')

    # ### end Alembic commands ###
