name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  lint:
    runs-on: ubuntu_latest


    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.9'

        
      - name: Install Dependencies
        uses: |
          pylint \
            --rcfile=.pylintrc \
            douglasblog/**/*.py \
            main.py \
            wsgi.py